version: "3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: todo-list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/src:/server/src
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 8080
      POSTGRES_DB: todo-list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
